name: Deploy Azure Postgres Flexible Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev, tst, uat, prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var-file="envs/${{ github.event.inputs.environment }}.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform apply -auto-approve -var-file="envs/${{ github.event.inputs.environment }}.tfvars"


      - name: Download dump from blob
        run: |
          az storage blob download \
            --account-name mystorage \
            --container-name db-dumps \
            --name huge_dump.dump \
            --file huge_dump.dump

      - name: Restore into Postgres
        run: |
          PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} pg_restore \
            -h ${{ secrets.PG_HOST }} \
            -U ${{ secrets.PG_USER }} \
            -d ${{ secrets.PG_DB }} \
            -j 4 \
            huge_dump.dump
