name: Create DNS Record

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/dns-record

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var-file=${{ github.event.inputs.environment }}.tfvars
        working-directory: terraform/dns-record

      - name: Terraform Output
        run: terraform output -json
        working-directory: terraform/dns-record
